version: '3.9'

services:
    mongodb:
        image: mongo:latest
        ports:
            - 27017:27017
        volumes:
            - ~/.docker-conf/mongo/data/pagaleve:/data/db
        environment:
            - MONGO_INITDB_ROOT_USERNAME=pagaleve
            - MONGO_INITDB_ROOT_PASSWORD=pagalevePass
